### ISSUE TITLE
流式语音合成的问题

### ISSUE THREAD

**Issue by Cuanmaomao** [aliyun/alibabacloud-nls-python-sdk#7]
测试test_stream_input_tts.py文件
出现了：nls.exception.WrongStateException: send with wrong state 6的报错
请教一下，有办法解决吗？

**Comment by lengjiayi** [comment]
> 测试test_stream_input_tts.py文件 出现了：nls.exception.WrongStateException: send with wrong state 6的报错 请教一下，有办法解决吗？

猜测是默认音色longxiaochun还不支持流式调用，可以切换成官网目前支持的音色试试看

**Comment by liangyy0** [comment]
我也遇到了同样的问题，改发音人还是报一样的错，有人知道是什么问题吗

**Comment by lengjiayi** [comment]
请问on_error回调函数有打印信息吗，可以贴出来看看
